### ISSUE TITLE
doesn't work for all pairs

### ISSUE THREAD

**Issue by jonorthwash** [unhammer/apertium-get#12]
Some pairs fail (see below).  This might be a bug of the pairs and not `apertium-get` though?

```
butter[~/ling073]$ apertium-get apertium-ita-srd
Cloning into 'apertium-ita-srd'...
remote: Enumerating objects: 10, done.
remote: Total 10 (delta 0), reused 0 (delta 0), pack-reused 10
Unpacking objects: 100% (10/10), 1.93 KiB | 23.00 KiB/s, done.
Traceback (most recent call last):
  File "/bin/apertium-get", line 394, in <module>
    main()
  File "/bin/apertium-get", line 358, in main
    try_to_clone(dep, args.depth, args.keep_going, args.ssh)
  File "/bin/apertium-get", line 227, in try_to_clone
    get_deps(dep)
  File "/bin/apertium-get", line 127, in get_deps
    with open(dep_paths[pair] + "/configure.ac") as conf:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwashin1/ling073/apertium-ita-srd/configure.ac'
```

**Comment by mr-martian** [comment]
ita-srd is nearly empty, and should probably be deleted given the existence of srd-ita, so yes, this is a language bug not a -get bug.

**Comment by TinoDidriksen** [comment]
ita-srd is now archived and I've set its URL to srd-ita. The nightly builder's discovery script ignores archived repos and repos that lack `configure.ac` - apertium-get should probably do the same.

**Comment by jonorthwash** [comment]
> The nightly builder's discovery script ignores archived repos and repos that lack `configure.ac` - apertium-get should probably do the same.

Yes, this sounds like a good solution.

Also, the current error message is useful to experienced developers, but not to new developers.  A better error message might be "This Apertium module has missing files.  Please report to the maintainer." or such.  But yes, a more important solution is for no pairs to have missing files / to not have pairs that are missing files.

**Comment by jonorthwash** [comment]
This is still an issue.  Even if you do `srd-ita`, it crashes—for some reason it tries to get `ita-srd` anyway??
